accounts/urls.py
from django.contrib import admin
from django.urls import path , include
from accounts import views
app_name  = 'accounts_app'
urlpatterns = [
    path('',views.user_login,name='index'),
    path('register/',views.register,name='register'),
   path('prompt/',views.prompt,name='prompt'), path('registerstudent/',views.registerstudent,name='registerstudent'), 
   path('registerlecturer/',views.registerlecturer,name='registerlecturer') ,
    path('login/',views.user_login,name='user_login'),
    path('logout/',views.user_logout,name='user_logout'),
    path('admin/', admin.site.urls),
    ]

exams/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views,urls
app_name = 'exams_app'
urlpatterns = [
    path('index/', views.index.as_view(),name='index'),
    path('addexam/', views.AddExam_view,name='addexam'),
    path('list/',views.listExams,name='list'),
    path('list/<int:pk>',views.ExamDetailView.as_view(),name='detail'),
    path('questionDetail/<int:pk>',views.QuestionDetailView.as_view(),name='questiondetail'),
    path('create/',views.ExamCreateView.as_view(),name='create'),
    path('createquestion/',views.QuestionCreateView.as_view(),name='createquestion'),
    path('update/<int:pk>',views.ExamUpdateView.as_view(),name='update'),
    path('updatequestion/<int:pk>',views.QuestionUpdateView.as_view(),name='updatequestion'),
    path('delete/<int:pk>',views.ExamDeleteView.as_view(),name='delete'),
    path('deletequestion/<int:pk>',views.QuestionDeleteView.as_view(),name='deletequestion'),

]
# urlpatterns = [
#     path('',views.index.as_view(),name='index'),
#     path('list/',views.ListGroups.as_view(),name='list'),
#     path('list/<int:pk>',views.SingleGroup.as_view(),name='detail'),
#     path('create/',views.CreateGroup.as_view(),name='create'),
#     path('createmember/',views.CreateGroupMember.as_view(),name='createmember'),
#     path('update/<int:pk>',views.GroupUpdateView.as_view(),name='update'),
#     path('delete/<int:pk>',views.GroupDeleteView.as_view(),name='delete'),
# ]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from myproject import views,urls
app_name = 'myproject_app'
urlpatterns = [
    path('admin/', admin.site.urls,name='admins'),
    path('',views.index,name='index'),
     path('studentsindex',views.studentsindex,name='studentsindex'),
    path('registergroup',views.registergroup.as_view(),name='registergroup'),
    path('accounts/',include('accounts.urls'),name='accounts'),
    path('questionbank/',include('questionbank.urls'),name='questionbank'),
    path('exams/',include('exams.urls'),name='exams'),
    path('groups/',include('groups.urls'),name='groups'),
    path('sittings/',include('sittings.urls'),name='sittings'),
    path('students/',include('students.urls'),name='students'),
    path('writeexams/',include('writeexam.urls'),name='writeexams')
]

exams/models.py
from django.db import models
from django.urls import reverse
from groups.models import Group
# Create your models here.
class Exam(models.Model):
    name = models.CharField(max_length=50,blank=False)
    code = models.CharField(unique=True,max_length=50,default='',blank=False)
    description = models.CharField(max_length=100,blank=True)
    group = models.ForeignKey(Group,null=True,related_name='Group',on_delete=models.SET_NULL)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('exams_app:detail',kwargs={'pk':self.pk})
class Question(models.Model):
    question = models.CharField(max_length=300)
    id=models.IntegerField(null=False,default=1,primary_key=True)
    a = models.CharField(max_length=150,null=True)
    b = models.CharField(max_length=150,null=True)
    c = models.CharField(max_length=150,null=True)
    d = models.CharField(max_length=150,null=True)
    answer = models.CharField(max_length=1,default='a',null=True)
    exam = models.ForeignKey(Exam,null=True,related_name='questions',on_delete=models.SET_NULL)
    def __str__(self):
        return self.question
    def get_absolute_url(self):
        return reverse('exams_app:list')

exams/forms.py
from django import forms
from .models import Exam
class AddExam(forms.ModelForm):
    class Meta():
        model = Exam
        fields = '__all__'

exams/views.py
from django.shortcuts import render
from django.views.generic import (View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView)
from exams.forms import AddExam
from django.urls import reverse,reverse_lazy
from groups.models import Group
from exams.models import Exam,Question
from code import getUserProfileInfo,checkifMember,addGroupMember,deleteGroupMemberRequest,deleteGroupMember , createGroupMember

# Create your views here.
def AddExam_view(request):
    form = AddExam()
    if request.method == 'POST':
        form = AddExam(data=request.POST)
        if form.is_valid():
            form.save(commit=True)
            return render(request,'index.html')
        else:
            print('ERROR FORM INVALID')
    return render(request,'exams/addexam.html',{'form':form})
class ExamListView(ListView):
    context_object_name = 'exams_list'
    model = Exam
def listExams(request):
    userid=request.user.pk
    num=getUserProfileInfo(userid)
    groups = Group.objects.all()
    exams = Exam.objects.all()
    data = set()
    examset = set()
    for group in groups:
        groupid = group.id
        userid=request.user.pk
        num=getUserProfileInfo(userid)
        result = checkifMember(num,groupid)
        if result:
            data.add(group)
    groups=data
    for exam in exams:
        examid=exam.id
        for group in groups:
            if exam.group.id == group.id :
                examset.add(exam)
    examsets=examset
    exam_list={'examset':examsets,'data':examset}
    return render(request,'exams/exam_list.html',context=exam_list)
# class SingleGroup(DetailView):
#     context_object_name = 'group_details'
#     model = Group
#     template_name = 'groups/group_detail.html'
class ExamDetailView(DetailView):
    context_object_name = 'exam_details'
    model = Exam
    template_name = 'exams/exam_detail.html'
class QuestionDetailView(DetailView):
    context_object_name = 'question_details'
    model = Question
    template_name = 'exams/question_detail.html'
class ExamCreateView(CreateView):
    fields=('name','code','description','group')
    model=Exam
class QuestionCreateView(CreateView):
    fields=('question','id','a','b','c','d','answer','exam')
    model=Question
class ExamUpdateView(UpdateView):
    context_object_name = 'exam_update'
    fields=('name','code','description','group')
    model=Exam
    template_name = 'exams/exam_form.html'
class QuestionUpdateView(UpdateView):
    context_object_name = 'question_update'
    fields=('question','id','a','b','c','d','answer','exam')
    model=Question
    template_name = 'exams/question_form.html'
class ExamDeleteView(DeleteView):
    context_object_name = 'exam_details'
    model=Exam
    success_url = reverse_lazy('exams_app:list')
class QuestionDeleteView(DeleteView):
    context_object_name = 'question_details'
    model=Question
    success_url = reverse_lazy('exams_app:list')
# class GroupUpdateView(UpdateView):
#     context_object_name = 'group_update'
#     fields=('name','description')
#     model=Group
#     template_name = 'groups/group_form.html'
# class GroupDeleteView(DeleteView):
#     context_object_name = 'group_details'
#     model=Group
#     success_url = reverse_lazy('groups_app:list')
class index(TemplateView):
    template_name = 'exams/index.html'

templates/exams/addexam.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}


</script>
{% if user.is_authenticated %}
<h1>username:{{user.username}}<br>usertype:{{user.registrationnumber}}<br>
{% if user.is_student  %}
<h1>Welcome To Add Exam Page!</h1>
<h3>
  <div class='container'>
    <form method='post'>
        {% csrf_token %}
        {{form.as_p}}
      <input type='submit'class='btn btn-primary value='Submit'>
    </form>
  </div>
 </h3>
 {% elif user.is_student %}
 <h1>You are  false , sorry</h1>
 {% else %}
 <h1>You are  false , sorry</h1>
 {% endif%}
{% else %}
<h1>please login to access this page </h1>
{% endif %}


{% endblock %}

templates/exams/exam_base.html
<html>
{% load static %}
<head>
<title>
{% block title_html %}{% endblock %}
</title>
<link rel='stylesheet'href={% static 'css/style.css'%}>
<link rel='stylesheet'href={% static 'bs/css/bootstrap.css'%}>
</head>
<body>
  <nav class ='navbar navbar-expand-lg-navbar-light bg-light 'align='center'>
      <div class='nav navbar-header'align='center'>
        <ul class='nav navbar-header'>
          <li><a class='navbar-brand'href='{% url 'exams_app:index'%}'>EXAMS MENU</a></li>
          <li><a class='navbar-brand'href='{% url 'exams_app:list' %}'>LIST EXAMS</a></li>
          <li><a class='navbar-brand'href='{% url 'exams_app:create' %}'>CREATE EXAM</a></li>
          <li><a class='navbar-brand'href='{% url 'exams_app:createquestion' %}'>CREATE QUESTION</a></li>
          <li><a class='navbar-brand'href='{% url 'index'%}'>MAIN MENU</a></li>
          {% if user.is_authenticated %}<img src={{user.profile_pic}} alt='404'/>
            <li><a class='navbar-link'href='{% url 'accounts_app:user_logout'%}'>Hello:{{user.username}} Logout</a></li>
          {% else %}<img src={% static 'images/img1.jpg'%}alt='login'/>
            <li><a class='navbar-link'href='{% url 'accounts_app:user_login'%}'>Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
<h1>
Exams Application Base Header- {% block body_block %}{% endblock %}
</h1>
<article>
{% block article_content %}{% endblock %}
<h3>Exams Application Base Footer</h3>
</article>
</body>
</html>

templates/exams/exam_confirm_delete.html
{% extends 'exams/exam_base.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Exam Delete View!</h1>
<h2>Delete {{exam_details.name}}?</h2>
<form method = 'post'>
  {% csrf_token %}
  <input type='submit' class='btn btn-danger'value='Delete'>
  <a href='{% url 'exams_app:detail' pk=exam_details.pk %}'>Cancel</a>
</form>
{% endblock %}

templates/exams/exam_detail.html
{% extends 'exams/exam_base.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Exam Detail View!</h1>
<h2>Exam Details:</h2>
<p>Name:{{exam_details.name}}</p>
<p>Exam Code:{{exam_details.code}}</p>
<p>Description:{{exam_details.description}}</p>
<p>Exam Group:{{exam_details.group}}</p>
<div class='container'>
  <p><a class ='btn btn-warning'href='{% url 'exams_app:update' pk=exam_details.pk %}'>Update</a></p>
</div>
<div class='container'>
  <p><a class ='btn btn-danger'href='{% url 'exams_app:delete' pk=exam_details.pk %}'>Delete</a></p>
</div>
<h3>Questions:</h3>
{% for question in exam_details.questions.all %}
<p>{{question.question}} </p>
<div class='container'>
  <p><a class ='btn btn-warning'href='{% url 'exams_app:questiondetail' pk=question.pk %}'>Edit</a></p>
</div>

{% endfor %}
{% endblock %}

templates/exams/exam_form.html
{% extends 'exams/exam_base.html' %}
{% load static %}
{% block body_block %}
<h1>Welcome To Exam Form!<br>
{% if not form.instance.pk %}
Create Exam
{% else %}
Update Exam
{% endif %}
</h1>
<form method = 'post'>
  {% csrf_token %}
  {{ form.as_p }}
  <input type='submit' class='btn btn-primary'value='submit'>

{% endblock %}

templates/exams/exam_list.html
{% extends 'exams/exam_base.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Exam List View !</h1>
<ol>
  {% for exam in examset %}
  <h2><li><a href='{{exam.id}}'>{{exam.name}}</a></li></h2>
  {% endfor %}

{% endblock %}

templates/exams/index.html
{% extends 'students/students_base.html' %}
{% load static %}
{% block body_block %}
<h1>Welcome To Students Index Form!<br>

{% endblock %}

templates/exams/question_confirm_delete.html
{% extends 'exams/exam_base.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Question Delete View!</h1>
<h2>Delete {{question_details.question}}?</h2>
<form method = 'post'>
  {% csrf_token %}
  <input type='submit' class='btn btn-danger'value='Delete'>
  <a href='{% url 'exams_app:list'  %}'>Cancel</a>
</form>
{% endblock %}

templates/exams/question_detail.html
{% extends 'exams/exam_base.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Question Detail View!</h1>
<h2>Question Details:</h2>
<p>Question:{{question_details.question}}</p>
<p>ID:{{question_details.id}}</p>
<p>A:{{question_details.a}}</p>
<p>B:{{question_details.b}}</p>
<p>C:{{question_details.c}}</p>
<p>D:{{question_details.d}}</p>
<p>Answer:{{question_details.answer}}</p>
<p>Exam:{{question_details.exam}}</p>
<div class='container'>
  <p><a class ='btn btn-warning'href='{% url 'exams_app:updatequestion' pk=question_details.pk %}'>Update</a></p>
</div>
<div class='container'>
  <p><a class ='btn btn-danger'href='{% url 'exams_app:deletequestion' pk=question_details.pk %}'>Delete</a></p>
</div>
{% endblock %}

templates/exams/question_form.html
{% extends 'exams/exam_base.html' %}
{% load static %}
{% block body_block %}
<h1>Welcome To Create Question Form!<br>
{% if not form.instance.pk %}
Create Question
{% else %}
Update Question
{% endif %}
</h1>
<form method = 'post'>
  {% csrf_token %}
  {{ form.as_p }}
  <input type='submit' class='btn btn-primary'value='submit'>

{% endblock %}