accounts/urls.py
from django.contrib import admin
from django.urls import path , include
from accounts import views
app_name  = 'accounts_app'
urlpatterns = [
    path('',views.user_login,name='index'),
    path('register/',views.register,name='register'),
   path('prompt/',views.prompt,name='prompt'), path('registerstudent/',views.registerstudent,name='registerstudent'), 
   path('registerlecturer/',views.registerlecturer,name='registerlecturer') ,
    path('login/',views.user_login,name='user_login'),
    path('logout/',views.user_logout,name='user_logout'),
    path('admin/', admin.site.urls),
    ]

exams/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views,urls
app_name = 'exams_app'
urlpatterns = [
    path('index/', views.index.as_view(),name='index'),
    path('addexam/', views.AddExam_view,name='addexam'),
    path('list/',views.listExams,name='list'),
    path('list/<int:pk>',views.ExamDetailView.as_view(),name='detail'),
    path('questionDetail/<int:pk>',views.QuestionDetailView.as_view(),name='questiondetail'),
    path('create/',views.ExamCreateView.as_view(),name='create'),
    path('createquestion/',views.QuestionCreateView.as_view(),name='createquestion'),
    path('update/<int:pk>',views.ExamUpdateView.as_view(),name='update'),
    path('updatequestion/<int:pk>',views.QuestionUpdateView.as_view(),name='updatequestion'),
    path('delete/<int:pk>',views.ExamDeleteView.as_view(),name='delete'),
    path('deletequestion/<int:pk>',views.QuestionDeleteView.as_view(),name='deletequestion'),

]
# urlpatterns = [
#     path('',views.index.as_view(),name='index'),
#     path('list/',views.ListGroups.as_view(),name='list'),
#     path('list/<int:pk>',views.SingleGroup.as_view(),name='detail'),
#     path('create/',views.CreateGroup.as_view(),name='create'),
#     path('createmember/',views.CreateGroupMember.as_view(),name='createmember'),
#     path('update/<int:pk>',views.GroupUpdateView.as_view(),name='update'),
#     path('delete/<int:pk>',views.GroupDeleteView.as_view(),name='delete'),
# ]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from myproject import views,urls
app_name = 'myproject_app'
urlpatterns = [
    path('admin/', admin.site.urls,name='admins'),
    path('',views.index,name='index'),
     path('studentsindex',views.studentsindex,name='studentsindex'),
    path('registergroup',views.registergroup.as_view(),name='registergroup'),
    path('accounts/',include('accounts.urls'),name='accounts'),
    path('questionbank/',include('questionbank.urls'),name='questionbank'),
    path('exams/',include('exams.urls'),name='exams'),
    path('groups/',include('groups.urls'),name='groups'),
    path('sittings/',include('sittings.urls'),name='sittings'),
    path('students/',include('students.urls'),name='students'),
    path('writeexams/',include('writeexam.urls'),name='writeexams')
]

sittings/urls.py
from django.contrib import admin
from django.urls import path, include
from sittings import views
app_name = 'sittings_app'
urlpatterns = [
    path('', views.index.as_view(),name='index'),
    path('list/',views.listSitting,name='list'),
    path('list/<int:pk>',views.SittingDetailView.as_view(),name='detail'),
    path('update/<int:pk>',views.SittingUpdateView.as_view(),name='update'),
    path('updatecandidate/<int:pk>',views.CandidateUpdateView.as_view(),name='updatecandidate'),
    path('delete/<int:pk>',views.SittingDeleteView.as_view(),name='delete'),
    path('deletecandidate/<int:pk>',views.CandidateDeleteView.as_view(),name='deletecandidate'),
    path('deletecandidaterequest/<int:pk>',views.CandidateRequestDeleteView.as_view(),name='deletecandidaterequest'),
    path('create/',views.SittingCreateView.as_view(),name='create'),
    path('createcandidate/',views.CandidateCreateView.as_view(),name='createcandidate'),
    path('addcandidate/',views.AddCandidateView,name='addcandidate'),
    path('candidateDetail/<int:pk>',views.CandidateDetailView.as_view(),name='candidatedetail'),
    path('candidaterequestDetail/<int:pk>',views.CandidateRequestDetailView.as_view(),name='candidaterequestdetail'),
]

sittings/models.py
from django.db import models
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django import template
from django.urls import reverse
from exams.models import Exam
from accounts.models import UserProfileInfo
User=get_user_model()
register = template.Library()
# Create your models here.
class Sitting(models.Model):
    name = models.CharField(blank=False,default='',max_length=100)
    id = models.IntegerField(null=False,default=1,primary_key=True,unique=True)
    description = models.TextField(blank=True,default='')
    exam = models.ForeignKey(Exam,null=True,related_name='exams',on_delete=models.SET_NULL)
    length = models.CharField(blank=True,default='',max_length=100)
    schedule = models.DateTimeField(verbose_name='schedule',null=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('sittings_app:detail',kwargs={'pk':self.pk})
class Candidate(models.Model):
    sitting = models.ForeignKey(Sitting,null=True,related_name='candidates',on_delete=models.SET_NULL)
    user = models.ForeignKey(UserProfileInfo,null=True,related_name='user_sittings',on_delete=models.SET_NULL)
    def __str__(self):
        return self.user.user.username
    def get_absolute_url(self):
        return reverse('sittings_app:list')
class CandidateRequests(models.Model):
    sitting = models.ForeignKey(Sitting,null=True,related_name='candidaterequests',on_delete=models.SET_NULL)
    user = models.ForeignKey(UserProfileInfo,null=True,related_name='user_sittingrequests',on_delete=models.SET_NULL)
    def __str__(self):
        return self.user.user.username
    def get_absolute_url(self):
        return reverse('sittings_app:list')

sittings/views.py
from django.shortcuts import render
from django.views.generic import (View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView)
from exams.forms import AddExam
from django.urls import reverse,reverse_lazy
from .models import Sitting,Candidate,CandidateRequests
from groups.models import Group
from code import addCandidate , getUserProfileInfo , checkifMember
# from sittings.models import Sitting , Candidate , CandidateRequests
# def AddMember(request):
#     data = request.POST.get('name')
#     iddata = request.POST.get('id')
#     newuser = addGroupMember(iddata)
#     print(newuser)
#     my_dict = {}
#     return render(request,'index.html',context=my_dict)
def AddCandidateView(request):
    data = request.POST.get('candidaterequestid')
    newuser = addCandidate(data)
    print(newuser)
    my_dict = {}
    return render(request,'sittings/index.html',context=my_dict)
class SittingListView(ListView):
    context_object_name = 'sitting_list'
    model = Sitting
def listSitting(request):
    userid=request.user.pk
    num=getUserProfileInfo(userid)
    groups = Group.objects.all()
    print(groups)
    sittings = Sitting.objects.all()
    data = set()
    sittingset = set()
    for group in groups:
        groupid = group.id
        userid=request.user.pk
        num=getUserProfileInfo(userid)
        result = checkifMember(num,groupid)
        if result:
            data.add(group)
    groups=data
    for sitting in sittings:
        sittinggroup=sitting.exam.group.id
        print(sittinggroup)
        for group in groups:
            if sitting.exam.group.id == group.id :
                sittingset.add(sitting)
    sittings=sittingset
    print(groups)
    print(sittings)
    sitting_list={'sittings':sittings}
    return render(request,'sittings/sitting_list.html',context=sitting_list)
# # class SingleGroup(DetailView):
# #     context_object_name = 'group_details'
# #     model = Group
# #     template_name = 'groups/group_detail.html'
class SittingDetailView(DetailView):
    context_object_name = 'sitting_details'
    model = Sitting
    template_name = 'sittings/sitting_detail.html'
class CandidateDetailView(DetailView):
    context_object_name = 'candidate_details'
    model = Candidate
    template_name = 'sittings/candidate_detail.html'
class CandidateRequestDetailView(DetailView):
    context_object_name = 'candidaterequest_details'
    model = CandidateRequests
    template_name = 'sittings/candidaterequest_detail.html'
class SittingCreateView(CreateView):
    fields=('name','id','description','exam','length','schedule')
    model=Sitting
class CandidateCreateView(CreateView):
    fields=('user','sitting')
    model=Candidate
class SittingUpdateView(UpdateView):
    context_object_name = 'sitting_update'
    fields=('name','id','description','exam','length','schedule')
    model=Sitting
    template_name = 'sittings/sitting_form.html'
class CandidateUpdateView(UpdateView):
    context_object_name = 'candidate_update'
    fields=('user','sitting')
    model=Candidate
    template_name = 'sittings/candidate_form.html'
# class QuestionUpdateView(UpdateView):
#     context_object_name = 'question_update'
#     fields=('question','id','a','b','c','d','answer','exam')
#     model=Question
#     template_name = 'exams/question_form.html'
class SittingDeleteView(DeleteView):
    context_object_name = 'sitting_details'
    model=Sitting
    success_url = reverse_lazy('sittings_app:list')
class CandidateDeleteView(DeleteView):
    context_object_name = 'candidate_details'
    model=Candidate
    success_url = reverse_lazy('sittings_app:list')
class CandidateRequestDeleteView(DeleteView):
    context_object_name = 'candidaterequest_details'
    model=CandidateRequests
    success_url = reverse_lazy('sittings_app:list')
# # class GroupUpdateView(UpdateView):
# #     context_object_name = 'group_update'
# #     fields=('name','description')
# #     model=Group
# #     template_name = 'groups/group_form.html'
# # class GroupDeleteView(DeleteView):
# #     context_object_name = 'group_details'
# #     model=Group
# #     success_url = reverse_lazy('groups_app:list')
class index(TemplateView):
    template_name = 'sittings/index.html'

templates/sittings/candidate_confirm_delete.html
{% extends 'sittings/sittingsbase.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Candidate Delete View!</h1>
<h2>Delete {{candidate_details.name}}?</h2>
<form method = 'post'>
  {% csrf_token %}
  <input type='submit' class='btn btn-danger'value='Delete'>
  <a href='{% url 'sittings_app:list' %}'>Cancel</a>
</form>
{% endblock %}

templates/sittings/candidate_detail.html
{% extends 'sittings/sittingsbase.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Candidate Detail View!</h1>
<h2>Candidate Details:</h2>
<p>Name:{{candidate_details.user.user.username}}</p>
<p>Sitting:{{candidate_details.sitting.name}}</p>

<div class='container'>
  <p><a class ='btn btn-warning'href='{% url 'sittings_app:updatecandidate' pk=candidate_details.pk %}'>Update</a></p>
</div>
<div class='container'>
  <p><a class ='btn btn-danger'href='{% url 'sittings_app:deletequestion' pk=candidate_details.pk %}'>Delete</a></p>
</div>
{% endblock %}

templates/sittings/candidate_form.html
{% extends 'sittings/sittingsbase.html' %}
{% load static %}
{% block body_block %}
<h1>Welcome To Candidate Form!<br>
{% if not form.instance.pk %}
Create Candidate
{% else %}
Update Candidate
{% endif %}
</h1>
<form method = 'post'>
  {% csrf_token %}
  {{ form.as_p }}
  <input type='submit' class='btn btn-primary'value='submit'>

{% endblock %}

templates/sittings/candidaterequest_detail.html
{% extends 'sittings/sittingsbase.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Candidate Request Detail View!</h1>
<h2>Candidate Request Details:</h2>
<p>Name:{{candidaterequest_details.user.user.username}}</p>
<p>Sitting:{{candidaterequest_details.sitting.name}}</p>

<div class='container'>
  <form method='POST'action={% url 'sittings_app:addcandidate'%}>
    {% csrf_token %}
    <input type='hidden'name='userid'value={{candidaterequest_details.user.user.id}}>
    <input type='hidden'name='sittingid'value={{candidaterequest_details.sitting.id}}>
        <input type='hidden'name='candidaterequestid'value={{candidaterequest_details.id}}>
   <input class='btn btn-primary'type='submit'value='Add'></form>

</div>
<div class='container'>
  <p><a class ='btn btn-danger'href='{% url 'sittings_app:deletecandidaterequest' pk=candidaterequest_details.pk %}'>Delete</a></p>
</div>

{% endblock %}

templates/sittings/candidaterequests_confirm_delete.html
{% extends 'sittings/sittingsbase.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Candidate Request Delete View!</h1>
<h2>Delete {{candidaterequests_details.name}}?</h2>
<form method = 'post'>
  {% csrf_token %}
  <input type='submit' class='btn btn-danger'value='Delete'>
  <a href='{% url 'sittings_app:list' %}'>Cancel</a>
</form>
{% endblock %}

templates/sittings/index.html
{% extends 'sittings/sittingsbase.html' %}
{% load static %}
{% block body_block %}
<h1>Welcome To Sittings Index Form!<br>

{% endblock %}

templates/sittings/sitting_confirm_delete.html
{% extends 'sittings/sittingsbase.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Sitting Delete View!</h1>
<h2>Delete {{sitting_details.name}}?</h2>
<form method = 'post'>
  {% csrf_token %}
  <input type='submit' class='btn btn-danger'value='Delete'>
  <a href='{% url 'sittings_app:list' %}'>Cancel</a>
</form>
{% endblock %}

templates/sittings/sitting_detail.html
{% extends 'sittings/sittingsbase.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Sitting Detail View!</h1>
<h2>Sitting Details:</h2>
<p>Name:{{sitting_details.name}}</p>
<p>Sitting ID:{{sitting_details.id}}</p>
<p>Description:{{sitting_details.description}}</p>
<p>Exam:{{sitting_details.exam}}</p>
<p>Length:{{sitting_details.length}}</p>
<p>Schedule:{{sitting_details.schedule}}</p>
<div class='container'>
  <p><a class ='btn btn-warning'href='{% url 'sittings_app:update' pk=sitting_details.pk %}'>Update</a></p>
</div>
<div class='container'>
  <p><a class ='btn btn-danger'href='{% url 'sittings_app:delete' pk=sitting_details.pk %}'>Delete</a></p>
</div>
<h3>Candidates Requests:</h3>
{% for candidate in sitting_details.candidaterequests.all %}
<p>Name:{{candidate.user.user.username}} </p>
<div class='container'>
  <p><a class ='btn btn-warning'href='{% url 'sittings_app:candidaterequestdetail' pk=candidate.pk %}'>Edit</a></p>
</div>
{% endfor %}
<h3>Candidates:</h3>
{% for candidate in sitting_details.candidates.all %}
<p>Name:{{candidate.user.user.username}} </p>
<div class='container'>
  <p><a class ='btn btn-warning'href='{% url 'sittings_app:candidatedetail' pk=candidate.pk %}'>Edit</a></p>
</div>

{% endfor %}
{% endblock %}

templates/sittings/sitting_form.html
{% extends 'sittings/sittingsbase.html' %}
{% load static %}
{% block body_block %}
<h1>Welcome To Create Sitting Form!<br>
{% if not form.instance.pk %}
Create Sitting
{% else %}
Update Sitting
{% endif %}
</h1>
<form method = 'post'>
  {% csrf_token %}
  {{ form.as_p }}
  <input type='submit' class='btn btn-primary'value='submit'>

{% endblock %}

templates/sittings/sitting_list.html
{% extends 'sittings/sittingsbase.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Sitting List View !</h1>
<ol>
  {% for sitting in sittings %}
  <h2><li><a href='{{sitting.id}}'>{{sitting.name}}</a></li></h2>
  {% endfor %}

{% endblock %}

templates/sittings/sittingsbase.html
<html>
{% load static %}
<head>
<title>
{% block title_html %}{% endblock %}
</title>
<link rel='stylesheet'href={% static 'css/style.css'%}>
<link rel='stylesheet'href={% static 'bs/css/bootstrap.css'%}>
</head>
<body>
  <nav class ='navbar navbar-expand-lg-navbar-light bg-light 'align='center'>
      <div class='nav navbar-header'align='center'>
        <ul class='nav navbar-header'>
          <li><a class='navbar-brand'href='{% url 'sittings_app:index'%}'>SITTINGS MENU</a></li>
          <li><a class='navbar-brand'href='{% url 'sittings_app:list'%}'>LIST SITTINGS</a></li>
          <li><a class='navbar-brand'href='{% url 'sittings_app:create'%}'>CREATE SITTING</a></li>
          <li><a class='navbar-brand'href='{% url 'sittings_app:createcandidate'%}'>CREATE CANDIDATE</a></li>
          <li><a class='navbar-brand'href='{% url 'index'%}'>MAIN MENU</a></li>
          {% if user.is_authenticated %}<img src={{user.profile_pic}} alt='404'/>
            <li><a class='navbar-link'href='{% url 'accounts_app:user_logout'%}'>Hello:{{user.username}} Logout</a></li>
          {% else %}<img src={% static 'images/img1.jpg'%}alt='login'/>
            <li><a class='navbar-link'href='{% url 'accounts_app:user_login'%}'>Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
<h1>
Sittings Application Base Header- {% block body_block %}{% endblock %}
</h1>
<article>
{% block article_content %}{% endblock %}
<h3>Sittings Application Base Footer</h3>
</article>
</body>
</html>