accounts/urls.py
from django.contrib import admin
from django.urls import path , include
from accounts import views
app_name  = 'accounts_app'
urlpatterns = [
    path('',views.user_login,name='index'),
    path('register/',views.register,name='register'),
   path('prompt/',views.prompt,name='prompt'), path('registerstudent/',views.registerstudent,name='registerstudent'), 
   path('registerlecturer/',views.registerlecturer,name='registerlecturer') ,
    path('login/',views.user_login,name='user_login'),
    path('logout/',views.user_logout,name='user_logout'),
    path('admin/', admin.site.urls),
    ]

exams/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views,urls
app_name = 'exams_app'
urlpatterns = [
    path('index/', views.index.as_view(),name='index'),
    path('addexam/', views.AddExam_view,name='addexam'),
    path('list/',views.listExams,name='list'),
    path('list/<int:pk>',views.ExamDetailView.as_view(),name='detail'),
    path('questionDetail/<int:pk>',views.QuestionDetailView.as_view(),name='questiondetail'),
    path('create/',views.ExamCreateView.as_view(),name='create'),
    path('createquestion/',views.QuestionCreateView.as_view(),name='createquestion'),
    path('update/<int:pk>',views.ExamUpdateView.as_view(),name='update'),
    path('updatequestion/<int:pk>',views.QuestionUpdateView.as_view(),name='updatequestion'),
    path('delete/<int:pk>',views.ExamDeleteView.as_view(),name='delete'),
    path('deletequestion/<int:pk>',views.QuestionDeleteView.as_view(),name='deletequestion'),

]
# urlpatterns = [
#     path('',views.index.as_view(),name='index'),
#     path('list/',views.ListGroups.as_view(),name='list'),
#     path('list/<int:pk>',views.SingleGroup.as_view(),name='detail'),
#     path('create/',views.CreateGroup.as_view(),name='create'),
#     path('createmember/',views.CreateGroupMember.as_view(),name='createmember'),
#     path('update/<int:pk>',views.GroupUpdateView.as_view(),name='update'),
#     path('delete/<int:pk>',views.GroupDeleteView.as_view(),name='delete'),
# ]

groups/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views,urls
app_name = 'groups_app'
urlpatterns = [
    path('',views.index.as_view(),name='index'),
    path('addmember/',views.AddMember,name='addmember'),
    path('list/',views.listGroups,name='list'),
    path('list/<int:pk>',views.SingleGroup.as_view(),name='detail'),
    path('memberdetail/<int:pk>',views.MemberDetailView.as_view(),name='memberdetail'),
    path('memberrequestdetail/<int:pk>',views.MemberRequestDetailView.as_view(),name='memberrequestdetail'),
    path('create/',views.creategroup,name='create'),
    path('createmember/',views.CreateGroupMember.as_view(),name='createmember'),
    path('update/<int:pk>',views.GroupUpdateView.as_view(),name='update'),
    path('updatemember/<int:pk>',views.MemberUpdateView.as_view(),name='updatemember'),
    path('delete/<int:pk>',views.GroupDeleteView.as_view(),name='delete'),
    path('deletemember/',views.MemberDeleteView,name='deletemember'),
    path('deletememberrequest/',views.MemberRequestDeleteView,name='deletememberrequest'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from myproject import views,urls
app_name = 'myproject_app'
urlpatterns = [
    path('admin/', admin.site.urls,name='admins'),
    path('',views.index,name='index'),
     path('studentsindex',views.studentsindex,name='studentsindex'),
    path('registergroup',views.registergroup.as_view(),name='registergroup'),
    path('accounts/',include('accounts.urls'),name='accounts'),
    path('questionbank/',include('questionbank.urls'),name='questionbank'),
    path('exams/',include('exams.urls'),name='exams'),
    path('groups/',include('groups.urls'),name='groups'),
    path('sittings/',include('sittings.urls'),name='sittings'),
    path('students/',include('students.urls'),name='students'),
    path('writeexams/',include('writeexam.urls'),name='writeexams')
]

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django import template
from django.urls import reverse
from accounts.models import UserProfileInfo
User=get_user_model()
register = template.Library()
# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=255,unique=True)
    description = models.TextField(blank=True,default='')
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('groups_app:detail',kwargs={'pk':self.pk})
class GroupMember(models.Model):
    group = models.ForeignKey(Group,null=True,related_name='memberships',on_delete=models.SET_NULL)
    user = models.ForeignKey(UserProfileInfo,null=True,related_name='user_groups',on_delete=models.SET_NULL)
    def __str__(self):
        return self.user.user.username
    def get_absolute_url(self):
        return reverse('groups_app:list')
class GroupMemberRequest(models.Model):
    group = models.ForeignKey(Group,null=True,related_name='membershipsrequest',on_delete=models.SET_NULL)
    user = models.ForeignKey(UserProfileInfo,null=True,related_name='user_groupsrequest',on_delete=models.SET_NULL)
    def __str__(self):
        return self.user.user.username
    def get_absolute_url(self):
        return reverse('groups_app:list')

groups/forms.py
from django import forms
from .models import Group

class AddGroup(forms.ModelForm):
    class Meta():
        model = Group
        fields = '__all__'

groups/views.py
from django.contrib.auth.mixins import (LoginRequiredMixin,PermissionRequiredMixin)
from django.urls import reverse,reverse_lazy
from django.views.generic import (View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView)
from django.views import generic
from code import getUserProfileInfo,checkifMember,addGroupMember,deleteGroupMemberRequest,deleteGroupMember , createGroupMember
from django.shortcuts import render
from .forms import AddGroup
from groups.models import Group,GroupMember,GroupMemberRequest
# Create your views here.
def AddMember(request):
    data = request.POST.get('name')
    iddata = request.POST.get('id')
    newuser = addGroupMember(iddata)
    print(newuser)
    my_dict = {}
    return render(request,'groups/index.html',context=my_dict)
def creategroup(request):
    form = AddGroup()
    if request.method == 'POST':
        form = AddGroup(data=request.POST)
        if form.is_valid():
            group=form.save(commit=True)
            group = group.id
            userid=request.user.pk
            num=getUserProfileInfo(userid)
            user = num.id
            newgroupmemberpk = createGroupMember(user,group)
            return render(request,'groups/index.html')
        else:
            print('ERROR FORM INVALID')
    return render(request,'groups/group_form.html',{'form':form})
def Creategroup(request):
    print('hello world')
    my_dict = {}
    return render(request,'groups/group_form.html',context=my_dict)
class CreateGroup(CreateView):
    fields = ('name','description')
    model = Group
class CreateGroupMember(CreateView):
    fields = ('group','user')
    model = GroupMember
class SingleGroup(DetailView):
    context_object_name = 'group_details'
    model = Group
    template_name = 'groups/group_detail.html'
class MemberDetailView(DetailView):
    context_object_name = 'member_details'
    model = GroupMember
    template_name = 'groups/memberrequest_detail.html'
class MemberRequestDetailView(DetailView):
    context_object_name = 'memberrequest_details'
    model = GroupMemberRequest
    template_name = 'groups/memberrequest_detail.html'
class ListGroups(ListView):
    context_object_name = 'group_list'
    model = Group
def listGroups(request):
    groups = Group.objects.all()
    data = set()
    for group in groups:
        groupid = group.id
        userid=request.user.pk
        num=getUserProfileInfo(userid)
        result = checkifMember(num,groupid)
        if result:
            data.add(group)
    groups=data
    group_list={'group':groups,'data':data}
    return render(request,'groups/group_list.html',context=group_list)
class GroupUpdateView(UpdateView):
    context_object_name = 'group_update'
    fields=('name','description')
    model=Group
    template_name = 'groups/group_form.html'
class MemberUpdateView(UpdateView):
    context_object_name = 'member_update'
    fields=('group','user')
    model=GroupMember
    template_name = 'groups/groupmember_form.html'
class GroupDeleteView(DeleteView):
    context_object_name = 'group_details'
    model=Group
    success_url = reverse_lazy('groups_app:list')
def MemberDeleteView(request):
    data = request.POST.get('name')
    iddata = request.POST.get('id')
    print(data)
    print(iddata)
    deleteGroupMember(iddata)
    return render(request,'groups/index.html')
def MemberRequestDeleteView(request):
    data = request.POST.get('name')
    iddata = request.POST.get('id')
    print(data)
    print(iddata)
    deleteGroupMemberRequest(iddata)
    return render(request,'groups_app:index')

# def AddMember(request):
#     data = request.POST.get('name')
#     iddata = request.POST.get('id')
#     newuser = addGroupMember(iddata)
#     print(newuser)
#     my_dict = {}
#     return render(request,'index.html',context=my_dict)

class index(TemplateView):
    template_name = 'groups/index.html'

templates/groups/group_confirm_delete.html
{% extends 'groups/groupbase.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Group Delete View!</h1>
<h2>Delete {{group_details.name}}?</h2>
<form method = 'post'>
  {% csrf_token %}
  <input type='submit' class='btn btn-danger'value='Delete'>
  <a href='{% url 'groups_app:detail' pk=group_details.pk %}'>Cancel</a>
</form>
{% endblock %}

templates/groups/group_detail.html
{% extends 'groups/groupbase.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Group Detail View!</h1>
<h2>Group  Details:</h2>
<p>Name:{{group_details.name}}</p>
<p>description:{{group_details.description}}</p>
<div class='container'>
  <p><a class ='btn btn-warning'href='{% url 'groups_app:update' pk=group_details.pk %}'>Update</a></p>
</div>
<div class='container'>
  <p><a class ='btn btn-danger'href='{% url 'groups_app:delete' pk=group_details.pk %}'>Delete</a></p>
</div>
<h3>Membership Requests:</h3>
{% for GroupMember in group_details.membershipsrequest.all %}
<p>Name:{{GroupMember.user.user}} </p>
<div class='container'>
  <p><a class ='btn btn-warning'href='{% url 'groups_app:memberrequestdetail' pk=GroupMember.pk %}'>Edit</a></p>
</div>
{% endfor %}
<h3>Members:</h3>
{% for GroupMember in group_details.memberships.all %}
<p>Name:{{GroupMember.user.user}} </p>
<form method='POST'action={% url 'groups_app:deletemember'%}>
  {% csrf_token %}
  <input type='hidden'name='name'value={{GroupMember.user}}>
  <input type='hidden'name='id'value={{GroupMember.pk}}>
 <input class='btn btn-danger'type='submit'value='Delete'></form>

</div>

{% endfor %}
{% endblock %}

templates/groups/group_form.html
{% extends 'groups/groupbase.html' %}
{% load static %}
{% block body_block %}
<h1>Welcome To Create Group Form!<br>
{% if not form.instance.pk %}
Create Group
{% else %}
Update Group
{% endif %}
</h1>
<form method = 'post'>
  {% csrf_token %}
  {{ form.as_p }}
  <input type='submit' class='btn btn-primary'value='submit'>

{% endblock %}

templates/groups/group_list.html
{% extends 'groups/groupbase.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Group List View !</h1>
<ol>
  {% for groups in group %}
  <h2><li><a href='{{groups.id}}'>{{groups.name}}</a></li></h2>
  {% endfor %}</ol>
  <h1><br><hr>{{group}}<br>{{data}}{{group.memberships}}</h1>

{% endblock %}

templates/groups/groupbase.html
<html>
{% load static %}
<head>
<title>
{% block title_html %}{% endblock %}
</title>
<link rel='stylesheet'href={% static 'css/style.css'%}>
<link rel='stylesheet'href={% static 'bs/css/bootstrap.css'%}>
</head>
<body>
  <nav class ='navbar navbar-expand-lg-navbar-light bg-light 'align='center'>
      <div class='nav navbar-header'align='center'>
        <ul class='nav navbar-header'>
          <li><a class='navbar-brand'href='{% url 'groups_app:index'%}'>GROUPS MENU</a></li>
          <li><a class='navbar-brand'href='{% url 'groups_app:list' %}'>LIST GROUPS</a></li>
          <li><a class='navbar-brand'href='{% url 'groups_app:create' %}'>CREATE GROUP</a></li>
              <li><a class='navbar-brand'href='{% url 'registergroup' %}'>REQUEST GROUPMEMBERSHIP</a></li>
          <!-- <li><a class='navbar-brand'href='{% url 'groups_app:createmember' %}'>CREATE GROUP MEMBER</a></li> -->
          <li><a class='navbar-brand'href='{% url 'index'%}'>MAIN MENU</a></li>
          {% if user.is_authenticated %}<img src={{user.profile_pic}} alt='404'/>
            <li><a class='navbar-link'href='{% url 'accounts_app:user_logout'%}'>Hello:{{user.username}} Logout</a></li>
          {% else %}<img src={% static 'images/img1.jpg'%}alt='login'/>
            <li><a class='navbar-link'href='{% url 'accounts_app:user_login'%}'>Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
<h1>
Groups Application Base Header- {% block body_block %}{% endblock %}
</h1>
<article>
{% block article_content %}{% endblock %}
<h3>Groups Application Base Footer</h3>
</article>
</body>
</html>

templates/groups/groupmember_confirm_delete.html
{% extends 'groups/groupbase.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Group Member Delete View!</h1>
<h2>Delete {{group_details.name}}?</h2>
<form method = 'post'>
  {% csrf_token %}
  <input type='submit' class='btn btn-danger'value='Delete'>
  <a href='{% url 'groups_app:list'  %}'>Cancel</a>
</form>
{% endblock %}

templates/groups/groupmember_form.html
{% extends 'groups/groupbase.html' %}
{% load static %}
{% block body_block %}
<h1>Welcome To Create Group Form!<br>
{% if not form.instance.pk %}
Create Group
{% else %}
Update Group
{% endif %}
</h1>
<form method = 'post'>
  {% csrf_token %}
  {{ form.as_p }}
  <input type='submit' class='btn btn-primary'value='submit'>

{% endblock %}

templates/groups/groupmemberrequest_form.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<h1>Welcome To Create Group Member Request Form!<br>
{% if not form.instance.pk %}
Create Group Member Request
{% else %}
Update Group Member Request
{% endif %}
</h1>
<form method = 'post'>
  {% csrf_token %}
  {{ form.as_p }}
  <input type='submit' class='btn btn-primary'value='submit'>

{% endblock %}

templates/groups/index.html
{% extends 'groups/groupbase.html' %}
{% load static %}
{% block body_block %}
<h1>Welcome To Groups Index Form!<br>

{% endblock %}

templates/groups/member_detail.html
{% extends 'groups/groupbase.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Group Member Detail View!</h1>
<h2>Group Member Details:</h2>
<p>Group:{{member_details.group}}</p>
<p>User:{{member_details.user}}</p>
<div class='container'>
  <p><a class ='btn btn-warning'href='{% url 'groups_app:updatemember' pk=member_details.pk %}'>Update</a></p>
</div>
<div class='container'>
  <p><a class ='btn btn-danger'href='{% url 'groups_app:deletemember' pk=member_details.pk %}'>Delete</a></p>
</div>

{% endblock %}

templates/groups/memberrequest_detail.html
{% extends 'groups/groupbase.html' %}
{% load static %}
{% block body_block %}


</script>
<h1>Welcome To Group Member Request View!</h1>
<h2>Group Member Request Details:</h2>
<p>User:{{memberrequest_details.user}}</p>
<div class='container'>
  <form method='POST'action={% url 'groups_app:addmember'%}>
    {% csrf_token %}
    <input type='hidden'name='name'value={{memberrequest_details.user}}>
    <input type='hidden'name='id'value={{memberrequest_details.pk}}>
   <input class='btn btn-primary'type='submit'value='Add'></form>

</div>
<div class='container'>
  <form method='POST'action={% url 'groups_app:deletememberrequest'%}>
    {% csrf_token %}
    <input type='hidden'name='name'value={{memberrequest_details.user}}>
    <input type='hidden'name='id'value={{memberrequest_details.pk}}>
   <input class='btn btn-danger'type='submit'value='Delete'></form>

</div>

{% endblock %}