accounts/urls.py
from django.contrib import admin
from django.urls import path , include
from accounts import views
app_name  = 'accounts_app'
urlpatterns = [
    path('',views.user_login,name='index'),
    path('register/',views.register,name='register'),
   path('prompt/',views.prompt,name='prompt'), path('registerstudent/',views.registerstudent,name='registerstudent'), 
   path('registerlecturer/',views.registerlecturer,name='registerlecturer') ,
    path('login/',views.user_login,name='user_login'),
    path('logout/',views.user_logout,name='user_logout'),
    path('admin/', admin.site.urls),
    ]

exams/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views,urls
app_name = 'exams_app'
urlpatterns = [
    path('index/', views.index.as_view(),name='index'),
    path('addexam/', views.AddExam_view,name='addexam'),
    path('list/',views.listExams,name='list'),
    path('list/<int:pk>',views.ExamDetailView.as_view(),name='detail'),
    path('questionDetail/<int:pk>',views.QuestionDetailView.as_view(),name='questiondetail'),
    path('create/',views.ExamCreateView.as_view(),name='create'),
    path('createquestion/',views.QuestionCreateView.as_view(),name='createquestion'),
    path('update/<int:pk>',views.ExamUpdateView.as_view(),name='update'),
    path('updatequestion/<int:pk>',views.QuestionUpdateView.as_view(),name='updatequestion'),
    path('delete/<int:pk>',views.ExamDeleteView.as_view(),name='delete'),
    path('deletequestion/<int:pk>',views.QuestionDeleteView.as_view(),name='deletequestion'),

]
# urlpatterns = [
#     path('',views.index.as_view(),name='index'),
#     path('list/',views.ListGroups.as_view(),name='list'),
#     path('list/<int:pk>',views.SingleGroup.as_view(),name='detail'),
#     path('create/',views.CreateGroup.as_view(),name='create'),
#     path('createmember/',views.CreateGroupMember.as_view(),name='createmember'),
#     path('update/<int:pk>',views.GroupUpdateView.as_view(),name='update'),
#     path('delete/<int:pk>',views.GroupDeleteView.as_view(),name='delete'),
# ]

groups/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views,urls
app_name = 'groups_app'
urlpatterns = [
    path('',views.index.as_view(),name='index'),
    path('addmember/',views.AddMember,name='addmember'),
    path('list/',views.listGroups,name='list'),
    path('list/<int:pk>',views.SingleGroup.as_view(),name='detail'),
    path('memberdetail/<int:pk>',views.MemberDetailView.as_view(),name='memberdetail'),
    path('memberrequestdetail/<int:pk>',views.MemberRequestDetailView.as_view(),name='memberrequestdetail'),
    path('create/',views.creategroup,name='create'),
    path('createmember/',views.CreateGroupMember.as_view(),name='createmember'),
    path('update/<int:pk>',views.GroupUpdateView.as_view(),name='update'),
    path('updatemember/<int:pk>',views.MemberUpdateView.as_view(),name='updatemember'),
    path('delete/<int:pk>',views.GroupDeleteView.as_view(),name='delete'),
    path('deletemember/',views.MemberDeleteView,name='deletemember'),
    path('deletememberrequest/',views.MemberRequestDeleteView,name='deletememberrequest'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from myproject import views,urls
app_name = 'myproject_app'
urlpatterns = [
    path('admin/', admin.site.urls,name='admins'),
    path('',views.index,name='index'),
     path('studentsindex',views.studentsindex,name='studentsindex'),
    path('registergroup',views.registergroup.as_view(),name='registergroup'),
    path('accounts/',include('accounts.urls'),name='accounts'),
    path('questionbank/',include('questionbank.urls'),name='questionbank'),
    path('exams/',include('exams.urls'),name='exams'),
    path('groups/',include('groups.urls'),name='groups'),
    path('sittings/',include('sittings.urls'),name='sittings'),
    path('students/',include('students.urls'),name='students'),
    path('writeexams/',include('writeexam.urls'),name='writeexams')
]

sittings/urls.py
from django.contrib import admin
from django.urls import path, include
from sittings import views
app_name = 'sittings_app'
urlpatterns = [
    path('', views.index.as_view(),name='index'),
    path('list/',views.listSitting,name='list'),
    path('list/<int:pk>',views.SittingDetailView.as_view(),name='detail'),
    path('update/<int:pk>',views.SittingUpdateView.as_view(),name='update'),
    path('updatecandidate/<int:pk>',views.CandidateUpdateView.as_view(),name='updatecandidate'),
    path('delete/<int:pk>',views.SittingDeleteView.as_view(),name='delete'),
    path('deletecandidate/<int:pk>',views.CandidateDeleteView.as_view(),name='deletecandidate'),
    path('deletecandidaterequest/<int:pk>',views.CandidateRequestDeleteView.as_view(),name='deletecandidaterequest'),
    path('create/',views.SittingCreateView.as_view(),name='create'),
    path('createcandidate/',views.CandidateCreateView.as_view(),name='createcandidate'),
    path('addcandidate/',views.AddCandidateView,name='addcandidate'),
    path('candidateDetail/<int:pk>',views.CandidateDetailView.as_view(),name='candidatedetail'),
    path('candidaterequestDetail/<int:pk>',views.CandidateRequestDetailView.as_view(),name='candidaterequestdetail'),
]

students/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views,urls
app_name = 'students_app'
urlpatterns = [
    path('',views.register,name='register'),
    path('mysittings',views.mySittings,name='mysittings'),
    path('<int:pk>',views.sittingdetails,name='sittingdetails'),
    path('deletesittingrequest/<int:pk>',views.deletesittingrequest,name='deletesittingrequest')

]

templates/base.html
<html>
{% load static %}
<link rel='stylesheet'href={% static 'nav.css'%}>
 <script src="{% static 'script.js' %}"></script>
 

 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

<head>
<title>
{% block title_html %}{% endblock %}
</title>

</head>
<body>
  <nav class ='Container'> 
    
      <div class='container'>
         
          
          
        <ul class='navbar-header'>
           <button class='bt'> <b class='idat'>IDAT</b> </button>
          <a class='navbar'href='{%url 'index'%}'>Home</a>
          <a class='navbar'href='{%url 'students_app:register'%}'>Students</a>
          <a class='navbar'href=''>About</a>
          <a class='navbar'href=''>Help</a>
          <a class='navbar'href=''>Feedback</a>

          {% if user.is_authenticated %}<img  src={{user.profile_pic.jpg}} alt='ohh noo its john cena '/>
        <a class='navbar-'href='{% url 'accounts_app:user_logout'%}'>Hello:{{user.username}} Logout</a>
          {% else %}<img src={% static 'images/img1.jpg'%}alt='login'/>
        <a class='navbar-'href='{% url 'accounts_app:user_login'%}'>Login</a>
          {% endif %}

          

            </ul>
          </div>
        </ul>
      </div>
    </nav>
<h1>
 {% block body_block %}{% endblock %}
</h1>
<article>
{% block article_content %}{% endblock %}
<hr><h3>Copyright AI Invigilator 2023</h3><hr>
</article>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}

<link rel='stylesheet'href={% static 'wlx.css'%}>
<div class='bod'>
<h1>WELCOME!</h1>
<div class='card'>

  {% if user.is_authenticated %}
    <h3>WELCOME back :{{user.username}} </h3>

  {% else %}
    <br>
    <h3> If you are New 
    <b class='idat'>  <div class="dropdown">
              <button class='log'><b class='ida'>Register</b></button>
              
              <div class="dropdown-content">
                <a class='cards'href='{% url 'accounts_app:registerlecturer'%}'>Lecturer</a>
                <br><a class='cards'href='{% url 'accounts_app:registerstudent'%}'>Student</a>
                
              </div>
            </div>
          
          </a><br><br></b> 

        


  </h3>


  


  {% endif %}

</div>
{% if user.is_athenticated %}
{% if lecturers %}
{{insert_me}}
{{lecturers}}

<div class='container'><h1>Lecturers Menu</h1>
<h3><li><a class='navbar-brand'href='{% url 'sittings_app:index' %}'>SITTINGS</a></li>
<h3><li><a class='navbar-brand'href='{% url 'exams_app:index' %}'>EXAM</a></li>
<li><a class='navbar-brand'href='{% url 'groups_app:index' %}'>GROUPS</a></li></h3>
</div>
{% endif %}
{{insert_me}}
{{lecturers}}

<div class='card'>

    <h3><a href='{% url 'registergroup'%}'>Register Your Relevant Group!</a><br> </h3>
{{usertype}}

</div>

</div>


{% endif %}
{% endblock %}

templates/lecturersbase.html
<html>
{% load static %}
<head>
<title>
{% block title_html %}{% endblock %}
</title>
<link rel='stylesheet'href={% static 'css/style.css'%}>
<link rel='stylesheet'href={% static 'nav.css'%}>
<link rel='stylesheet'href={% static 'bs/css/bootstrap.css'%}>
</head>
<body>
  <nav class ='Container'>
      <div class='container'>

        <div>
          <img class='imag' src={% static 'images/f.jpg'%} alt='img3'/>
        </div>
        <ul class='nav navbar-header'>

          <a class='navbar'href='{%url 'index'%}'>Home</a>
            <a class='navbar'href='{%url 'questionbank_app:index'%}'>QuestionBank</a>
            
          <a class='navbar'href='{%url 'students_app:register'%}'>Exams</a>
          <a class='navbar'href=''>Results</a>
          <a class='navbar'href=''>MyAccount</a>
          <a class='navbar'href=''>Feedback</a>
          
          {% if user.is_authenticated %}<img class='img' src={{user.profile_pic.jpg}} alt='ohh noo its john cena '/>
            <a class='logs'href='{% url 'accounts_app:user_logout'%}'>Hello:{{user.username}} Logout</a>
          {% else %}<img src={% static 'images/img1.jpg'%}alt='login'/>
            <a class='logs'href='{% url 'accounts_app:user_login'%}'>Login</a>
          {% endif %}

        </ul>
      </div>
    </nav>
<h1>
 {% block body_block %}{% endblock %}
</h1>
<article>
{% block article_content %}{% endblock %}
<hr><h3>Copyright AI Invigilator 2023</h3><hr>
</article>
</body>
</html>

templates/lecturersindex.html
{% extends 'lecturersbase.html' %}
{% load static %}
{% block body_block %}
<link rel='stylesheet'href={% static 'nav.css'%}>
<div>
    <img class='image' src={% static 'images/f.jpg'%} alt='img3'/>
  </div>






{% endblock %}

templates/studentsbase.html
<html>
{% load static %}
<head>
<title>
{% block title_html %}{% endblock %}
</title>
<link rel='stylesheet'href={% static 'css/style.css'%}>
<link rel='stylesheet'href={% static 'bs/css/bootstrap.css'%}>
</head>
<body>
  <nav class ='navbar navbar-expand-lg-navbar-light bg-light 'align='center'>
      <div class='nav navbar-header'align='center'>
        <ul class='nav navbar-header'>

          <li><a class='navbar-brand'href='{%url 'index'%}'>Home</a></li>
          <li><a class='navbar-brand'href='{%url 'students_app:register'%}'>Exams</a></li>
          <li><a class='navbar-brand'href=''>Results</a></li>
          <li><a class='navbar-brand'href=''>MyAccount</a></li>
          <li><a class='navbar-brand'href=''>Feedback</a></li>

          {% if user.is_authenticated %}<img src={{user.profile_pic.jpg}} alt='ohh noo its john cena '/>
            <li><a class='navbar-link'href='{% url 'accounts_app:user_logout'%}'>Hello:{{user.username}} Logout</a></li>
          {% else %}<img src={% static 'images/img1.jpg'%}alt='login'/>
            <li><a class='navbar-link'href='{% url 'accounts_app:user_login'%}'>Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
<h1>
 {% block body_block %}{% endblock %}
</h1>
<article>
{% block article_content %}{% endblock %}
<hr><h3>Copyright AI Invigilator 2023</h3><hr>
</article>
</body>
</html>

templates/studentsindex.html
{% extends 'studentsbase.html' %}
{% load static %}
{% block body_block %}
<h1>Students Portal!</h1>






{% endblock %}